### PR TITLE
Update dockerfile with best practices

### PR DESCRIPTION
**Pull request by HonkingGoose**
This commit updates this Dockerfile to follow best practices laid down here:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Changelog:
- Combine apt-get update with apt-get install in the same RUN statement.
- Sort multi-line arguments alphanumerically.
- Clean up the apt cache by removing /var/lib/apt/lists to reduce the image size.
- Grammar fixes.

### CODE REVIEW

**Comment by HonkingGoose** [comment]
Hi @veevidify Thanks for making this repository, and for making the explanation at https://dev.to/veevidify/docker-compose-up-your-entire-laravel-apache-mysql-development-environment-45ea

This is my way of helping this project forward, and giving some practical help. I'm new to Docker, but I noticed some things which are different from the Docker best practices linked above. I have made changes to be inline with the docker documentation linked above.

I'll gladly have your review for this pull-request. I hope it all works and I'm not breaking things.

**Review by veevidify — APPROVED** [review]
Hi,

Thanks for the PR. I agree with `apt-get update && apt-get install` being 1 image layer, therefore will merge.

As a future reference, this project is merely a bare-bone, working Laravel environment. I intend it for readers to clone and start developing off of it, OR use my Docker related changes as a reference to introduce Docker into their own Laravel projects. Therefore I wouldn't stress too much about things like order of packages alphabetically or grammatical accuracy.

**Comment by HonkingGoose** [comment]
Thanks for merging my work. 😄

**Comment by nwaweru** [comment]
Hi @veevidify, maybe you can mark the [repository as a template](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)?

This will give guys the idea that this is mearly a project to get you up and running with Docker + Laravel.

Just my two-cents.

**Pull request merged**
